#!/bin/sh

# 
# Copyright 2010 University of Southern California
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# set the services to run automatically?
chkconfig httpd on

# WSGI Socket Prefix
RUNDIR=/var/run/wsgi
mkdir -p ${RUNDIR}

# create local helper scripts
mkdir -p /etc/httpd/passwd

# allow slashes in URL
CONFFILE=/etc/httpd/conf.d/ssl.conf
if test -e $CONFFILE
then
	# save ssl.conf
	cp $CONFFILE $CONFFILE.`date +%F.%H:%M:%S`
	
	TMPFILE=`mktemp $CONFFILE.XXXXXX`
	cat $CONFFILE | sed 's/<\/VirtualHost>/\
	AllowEncodedSlashes On\
<\/VirtualHost>/' > $TMPFILE

	mv -f $TMPFILE $CONFFILE
fi

# disable python.conf file
CONFFILE=/etc/httpd/conf.d/python.conf
if test -e $CONFFILE
then
	mv $CONFFILE $CONFFILE.save
fi
	
# uncomment the LoadModule wsgi_module from wsgi.conf
CONFFILE=/etc/httpd/conf.d/wsgi.conf
if test -e $CONFFILE
then
	# save wsgi.conf
	cp $CONFFILE $CONFFILE.`date +%F.%H:%M:%S`
	
	TMPFILE=`mktemp $CONFFILE.XXXXXX`
	cat $CONFFILE | sed 's/^# LoadModule\(.*$\)/LoadModule\1/' > $TMPFILE
	
	mv -f $TMPFILE $CONFFILE
fi

service httpd restart
