#!/bin/sh

# support basic RSH args on top of runuser for local commands like rsync

in_options=true
TARGET_USER=

usage()
{
    cat <<E2OF
usage: $0 [-l <user>] hostname cmd [arg]...

Runs "cmd arg..." locally, using runuser if a target user is specified.
Hostname is ignored for compatibility with RSH for localhost.

E2OF
}

error()
{
    cat <<E2OF
$0: $@
E2OF
    usage
    exit 1
}

while [[ -n "${in_options}" ]]
do
  case "$1" in
      -l)
	  TARGET_USER="$2"
	  shift 2
	  ;;

      --)
	  shift
	  in_options=
	  ;;

      -*)
	  error Unsupported option flag "\"$1\"".
	  ;;

      *)
	  in_options=
	  ;;
  esac
done

# discard hostname
shift

[[ $# -gt 0 ]] || error Expected command and argument list

if [[ -n "${TARGET_USER}" ]]
then
    # run via runuser with target user
    commandstring="$1"
    shift

    for arg in "$@"
    do
      commandstring+=" \"$(sed -e 's/\"/\\\"/g' <<< "$arg")\""
    done

    runuser -c "${commandstring}" - "${TARGET_USER}"
else
    # run command directly since there is no target user to switch to
    exec "$@"
fi
